/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controls.CategoriesDAO;
import controls.CustomersDAO;
import controls.OrderdetailsDAO;
import controls.OrdersDAO;
import controls.ProductDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Customers;
import model.Orderdetails;
import model.Orders;

/**
 *
 * @author Brother
 */
public class OrderFrm extends javax.swing.JFrame {

    /**
     * Creates new form OrderFrm
     */
    public OrderFrm() {
        initComponents();
        loadcbxType();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxType = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPro = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        txtTongTien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtQuantityNew = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Loai San Pham");

        jLabel2.setText("Tim Kiem");

        jButton1.setText("Tim Kiem");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma San Pham", "Ten San Pham", "Hinh Anh", "Gia", "So Luong", "Mieu Ta", "Tinh Trang", "Ngay Nhap", "Loai San Pham"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPro);

        jLabel3.setText("So Luong");

        btnOrder.setText("Dua Vao Gio");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma San Pham", "Ten San Pham", "Don Gia", "So Luong", "Thanh Tien"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrder);

        txtTongTien.setEditable(false);

        jLabel4.setText("Tong Tien");

        jButton2.setText("Cap Nhat Thong Tin Khach Hang");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xoa Hang Khoi Gio");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Thay Doi Gio Hang");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setText("So Luong");

        jButton5.setText("Cap Nhat Gio Hang");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Ma Khach Hang");

        jLabel7.setText("Ten Khach Hang");

        jButton7.setText("Thanh Toan");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cbxType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnOrder)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtQuantityNew, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrder))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jLabel5)
                    .addComponent(txtQuantityNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton6)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ResultSet rs = null;
        ProductDAO od = new ProductDAO();
        if(txtSearch.getText().equals("")){
            if(cbxType.getSelectedIndex()==0){
                rs = od.search();
            }else{
                String type = cbxType.getSelectedItem().toString();
                rs = od.searchType(type);
            }
        }else{
            if(cbxType.getSelectedIndex()==0){
                String text = txtSearch.getText();
                rs = od.searchText(text);
            }else{
                String type = cbxType.getSelectedItem().toString();
                String text = txtSearch.getText();
                rs = od.searchTypeText(type, text);
            }
        }
        showtblPro(rs);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        int erro = 0;
        if(txtQuantity.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nhap so luong can mua!");
            erro = 1;
        }
        
        if(erro == 0){
            DefaultTableModel model = (DefaultTableModel) tblPro.getModel();
        int row = tblPro.getSelectedRow();
        
        int ID = Integer.parseInt(model.getValueAt(row, 0).toString());
        String name = model.getValueAt(row, 1).toString();
        int quantity = Integer.parseInt(txtQuantity.getText());
        double price = Double.parseDouble(model.getValueAt(row, 3).toString());
        double thanhtien = quantity*price;
        
        DefaultTableModel model2 = (DefaultTableModel) tblOrder.getModel();
        model2.addRow(new Object[]{ID, name, price, quantity, thanhtien});
        tblOrder.setModel(model2);
        txtQuantity.setText("");
        }
    }//GEN-LAST:event_btnOrderActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblOrder.getModel();
        int row = tblOrder.getSelectedRow();
        model.removeRow(row);
        //tblOrder.setModel(model);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblOrder.getModel();
        int row = tblOrder.getSelectedRow();
        
        txtQuantityNew.setText(model.getValueAt(row, 3).toString());       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int erro = 0;
        if(txtQuantityNew.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nhap so luong can mua!");
            erro = 1;
        }
        
        if(erro == 0){
            DefaultTableModel model = (DefaultTableModel) tblOrder.getModel();
        int row = tblOrder.getSelectedRow();
        
        double price = Double.parseDouble(model.getValueAt(row, 2).toString());
        int quantityNew = Integer.parseInt(txtQuantityNew.getText());
        double thanhtien = quantityNew*price;
        
        model.setValueAt(quantityNew, row, 3);
        model.setValueAt(thanhtien, row, 2);
        tblOrder.setModel(model);
        txtQuantityNew.setText("");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int erro = 0;
        if(txtID.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nhap ID khach hang!");
            erro = 1;
        }else if(txtName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nhap ten khach hang!");
            erro = 1;
        }
        
        if(erro == 0){
            int yes = 0;
            int ID = Integer.parseInt(txtID.getText());
            CustomersDAO cd = new CustomersDAO();
            ResultSet rs = cd.searchID();
            try {
                while(rs.next()){
                    if(rs.getInt("ID") == ID){
                        yes = 1;
                        break;
                    }
                }
            } catch (SQLException ex) {
                System.out.println(ex);
            }
           
            String name = txtName.getText();
            Customers c = new Customers();
            c.setID(ID);
            c.setName(name);
            if(yes == 0){
                cd.Add(c);
            }else if(yes == 1){
                cd.Update(c);
            }           
            JOptionPane.showMessageDialog(null, "Successfull");       
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int erro = 0;
        DefaultTableModel model = (DefaultTableModel) tblOrder.getModel();
        if(model.getDataVector().isEmpty()){
            JOptionPane.showMessageDialog(null, "Gio hang trong!");
            erro = 1;
        }else if(txtID.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nhap ID khach hang!");
            erro = 1;
        }else if(txtName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nhap ten khach hang!");
            erro = 1;
        }

        if(erro == 0){
            //Them orders vao csdl
        Calendar c = Calendar.getInstance();
        Date date = c.getTime();
        
        double tongtien = 0;
        int numRow = tblOrder.getRowCount();
        for(int i=0;i<numRow;i++){
            tongtien += Double.parseDouble(model.getValueAt(i, 4).toString());
        }       
        
        int cus_ID = Integer.parseInt(txtID.getText());
        Orders o = new Orders(date, tongtien, cus_ID);
        OrdersDAO cd = new OrdersDAO();
        cd.Add(o);
        
        //Them orderdetails vao csdl
        for(int i=0;i<numRow;i++){
            int quantity = Integer.parseInt(model.getValueAt(i, 3).toString());
            double sumPrice = Double.parseDouble(model.getValueAt(i, 4).toString());
            CustomersDAO cus = new CustomersDAO();
            ResultSet rs = cus.searchID_Orders(Integer.parseInt(txtID.getText()));
            int orders_ID = 0;
            try {
                while(rs.next()){
                    orders_ID = rs.getInt("id");
                }
            } catch (SQLException ex) {
                System.out.println(ex);
            }            
            int pro_ID = Integer.parseInt(model.getValueAt(i, 0).toString());
            
            Orderdetails ordetail = new Orderdetails(sumPrice, quantity, pro_ID, orders_ID);
            OrderdetailsDAO od = new OrderdetailsDAO();
            od.Add(ordetail);                      
        }
        
        txtTongTien.setText(String.valueOf(tongtien));
        JOptionPane.showMessageDialog(null, "Successfull");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        txtSearch.setText("");
        txtQuantity.setText("");
        txtQuantityNew.setText("");
        txtID.setText("");
        txtName.setText("");
        DefaultTableModel model = (DefaultTableModel) tblOrder.getModel();
        model.getDataVector().removeAllElements();
        tblOrder.setModel(model);
    }//GEN-LAST:event_jButton6ActionPerformed

    public void showtblPro(ResultSet rs){
        DefaultTableModel model = (DefaultTableModel) tblPro.getModel();
        model.getDataVector().removeAllElements();
        try {
            while(rs.next()){
                model.addRow(new Object[]{rs.getInt("ID"), rs.getString("name"), rs.getString("image"), rs.getDouble("price")
                , rs.getInt("quantity"), rs.getString("des"), rs.getString("status"), rs.getDate("adddate"), rs.getString("type")});
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        tblPro.setModel(model);
    }
    
    public void loadcbxType(){
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbxType.getModel();
        model.addElement("All");
        CategoriesDAO cd = new CategoriesDAO();
        ResultSet rs = cd.searchName();
        try {
            while(rs.next()){
                model.addElement(rs.getString("name"));
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        cbxType.setModel(model);
    }
    
    public void Canel(){

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrder;
    private javax.swing.JComboBox cbxType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTable tblPro;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtQuantityNew;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
